### ISSUE TITLE
Don`t work when language is jsx

### ISSUE THREAD

**Issue by Alan-QK** [walteribeiro/full-react-snippets#2]
[walter-ribeiro.full-react-snippets]:
 Unknown language in `contributes.full-react-snippets.language`. Provided value: jsx

【setting.json】
{
    "editor.snippetSuggestions": "top",
    ............
}

**Comment by walteribeiro** [comment]
Hi, do you can provide more information about this, for example when it occurs, it's a VScode error?

what's the type of your file in your IDE? 
![VSCode](https://user-images.githubusercontent.com/10420735/71887156-48e47b00-311c-11ea-8eac-a6012a505668.png)

**Comment by walteribeiro** [comment]
@qk0728 try to update the extension to 1.4.1
Thanks!

**Comment by Alan-QK** [comment]
Here is my file type. 
![image](https://user-images.githubusercontent.com/23489562/71943713-7a347800-31fc-11ea-903b-92d7f4667980.png)

====>
And...The current version of extension is 1.4.1.
![image](https://user-images.githubusercontent.com/23489562/71942722-23796f00-31f9-11ea-94c5-5e4b0a7a3925.png)

**Comment by Alan-QK** [comment]
But......The extension can work well in a TypeScript React file.

**Comment by walteribeiro** [comment]
try to reinstall because I remove the jsx from contributes in e1fa232fe2dde93e46caf90e1da086fc006c6377

**Comment by walteribeiro** [comment]
@qk0728 It worked?
