### ISSUE TITLE
PropTypes import and use mis-match

### ISSUE THREAD

**Issue by janus-crey** [walteribeiro/full-react-snippets#3]
When I use the shortcuts for React components with PropTypes, they get imported with an uppercase "P" but used with a lowercase "p".

```
import React from 'react'
import PropTypes from 'prop-types'

const componentName = () => {
  return (
    <>
      
    </>
  )
}

componentName.propTypes = {

}

export default componentName
```

**Comment by walteribeiro** [comment]
The instance of a PropTypes object is lowercase, but the Class/Type is uppercase. The instance is componentName.propTypes. The Class/Type is PropTypes.

For example:

    import React from 'react'
    import PropTypes from 'prop-types'

    const componentName = () => {
      return (
        <>
      
        </>
      )
    }

    componentName.propTypes = {
        username: PropTypes.string.isRequired,
    }

    export default componentName

you got it?

**Comment by janus-crey** [comment]
Ah yes sorry
